# ==============================================================
# = GestUser - Servizio Gestione Utenti 
# ==============================================================

server:
  port: 8019
spring:
  application:
    name: GestUser
# ==============================================================
# = MONGODB Parameters
# ==============================================================
  data:
    mongodb:
      authentication-database: admin
      database: gestfid
      host: localhost
      password: WebClient
      port: 27017
      username: WebClient
